const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');
const { Pool } = require('pg');

test('Postgres: jobs, isolation and one-time local developer bootstrap', { skip: !process.env.LEMON_TEST_DATABASE_URL }, async (t) => {
  const connection = new URL(process.env.LEMON_TEST_DATABASE_URL);
  assert.ok(['127.0.0.1','localhost'].includes(connection.hostname), 'Test databases must be local');
  const admin = new Pool({ connectionString: connection.href });
  const schema = 'verify_' + crypto.randomBytes(8).toString('hex');
  await admin.query(`CREATE SCHEMA ${schema}`);
  connection.searchParams.set('options', `-c search_path=${schema}`);
  process.env.DATABASE_URL = connection.href;
  const { database, close } = require('./db.cjs');
  t.after(async () => { await close(); await admin.end(); });
  await database().query(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'));
  const { enqueue, getJob, claim, transition, runOne } = require('./jobs.cjs');
  const { insertPet, ownedPet, updatePet } = require('./pets.cjs');
  const { bootstrapDeveloper, viewer } = require('./auth.cjs');
  const user = crypto.randomUUID(), other = crypto.randomUUID();
  await database().query('INSERT INTO users(id,email,password_hash,credits) VALUES($1,$2,$3,100),($4,$5,$3,0)', [user,'a@test.invalid','not-a-login',other,'b@test.invalid']);
  await insertPet({id:'animation-writeback',ownerId:user,results:[{style:'fixture',imageUrl:'fixture'}]});
  const [a,b] = await Promise.all([enqueue(user,'animate','same-request-key-0001',{imageUrl:'fixture'},'test'), enqueue(user,'animate','same-request-key-0001',{imageUrl:'fixture'},'test')]);
  assert.equal(a.id,b.id);
  assert.equal((await database().query('SELECT credits FROM users WHERE id=$1',[user])).rows[0].credits,90);
  await assert.rejects(enqueue(user,'animate','same-request-key-0001',{imageUrl:'different'},'test'), { status: 409 });
  await assert.rejects(enqueue(other,'animate','no-credit-request-001',{},'test'), { status: 402 });
  assert.equal(await getJob(other,a.id),null);
  const worker1 = crypto.randomUUID(), worker2 = crypto.randomUUID();
  const [lease1,lease2] = await Promise.all([claim(worker1),claim(worker2)]);
  const lease = lease1 || lease2;
  assert.equal([lease1,lease2].filter(Boolean).length,1);
  await transition(lease,'polling',{ upstreamId:'upstream-original' });
  await database().query("UPDATE generation_jobs SET locked_by=$1,lease_until=now()-interval '1 second' WHERE id=$2",[worker1,a.id]);
  let submissions = 0, polls = 0;
  const adapter = { submit: async () => { submissions++; throw new Error('Must not submit again'); }, poll: async (job) => { polls++; assert.equal(job.upstream_id,'upstream-original'); return { result:{ videoUrl:'synthetic' } }; }, materialize: async () => ({ videoUrl:'/api/assets/fixture' }) };
  await runOne(adapter,worker2);
  await runOne(adapter,worker2);
  assert.equal(submissions,0); assert.equal(polls,1);
  assert.equal((await getJob(user,a.id)).state,'success');
  assert.equal((await ownedPet(user,'animation-writeback')).archive.results[0].videoUrl,'/api/assets/fixture','completed animation survives a closed browser');
  await assert.rejects(transition(lease,'failed'), /lease lost/);
  const uncertain = await enqueue(user,'animate','uncertain-request-001',{},'test');
  await claim(worker1);
  await database().query("UPDATE generation_jobs SET lease_until=now()-interval '1 second' WHERE id=$1",[uncertain.id]);
  assert.equal(await claim(worker2),null);
  assert.equal((await getJob(user,uncertain.id)).state,'needs_review');
  const sameUncertain = await enqueue(user,'animate','new-key-same-input-01',{},'test');
  assert.equal(sameUncertain.id,uncertain.id,'refresh/retry with a new key must not duplicate uncertain work');
  const rejected = await enqueue(user,'animate','rejected-request-0001',{scene:'known-rejection'},'test');
  await runOne({ submit: async () => { throw Object.assign(new Error('Rejected before charging'),{safeToRefund:true}); } },worker2);
  assert.equal((await getJob(user,rejected.id)).state,'failed');
  const ledger = await database().query('SELECT reason,count(*) FROM usage_ledger WHERE job_id=$1 GROUP BY reason',[rejected.id]);
  assert.deepEqual(Object.fromEntries(ledger.rows.map((r)=>[r.reason,r.count])),{reserve:'1',refund:'1'});
  await insertPet({id:'fixturepet',ownerId:user,petName:'original',results:[]});
  const original = await ownedPet(user,'fixturepet');
  await assert.rejects(ownedPet(other,'fixturepet'), { status:404 });
  const changes = await Promise.allSettled([updatePet(user,'fixturepet',original.version,{...original.archive,petName:'first'}),updatePet(user,'fixturepet',original.version,{...original.archive,petName:'second'})]);
  assert.equal(changes.filter((r)=>r.status==='fulfilled').length,1);
  const crashed = await enqueue(user,'animate','process-crash-request-1',{imageUrl:'fixture'},'test');
  const child = spawnSync(process.execPath, ['-e', `const {claim,transition}=require('./lib/server/jobs.cjs');(async()=>{const job=await claim(require('node:crypto').randomUUID());await transition(job,'polling',{upstreamId:'upstream-original'});process.exit(17)})().catch(()=>process.exit(1))`], { cwd:process.cwd(), env:process.env, windowsHide:true, encoding:'utf8' });
  assert.equal(child.status,17,'child exits abruptly after checkpointing its upstream ID');
  await runOne(adapter,worker2);
  await runOne(adapter,worker2);
  assert.equal((await getJob(user,crashed.id)).state,'success');
  assert.equal(submissions,0,'new worker never resubmits the crashed process job');
  const originalOrigin = process.env.APP_ORIGIN;
  process.env.APP_ORIGIN = 'http://127.0.0.1:3000';
  t.after(() => { process.env.APP_ORIGIN = originalOrigin; });
  const developer = await bootstrapDeveloper({ email: 'developer@test.invalid', password: 'Developer@2026' });
  assert.equal(developer.user.isAdmin, true);
  const developerSession = await viewer(new Request('http://127.0.0.1:3000/api/auth/me', { headers: { cookie: developer.cookie.split(';')[0] } }));
  assert.equal(developerSession.isAdmin, true, 'bootstrap session carries the admin role');
  await assert.rejects(bootstrapDeveloper({ email: 'second@test.invalid', password: 'Developer@2026' }), { status: 409 });
  process.env.APP_ORIGIN = 'https://example.invalid';
  await assert.rejects(bootstrapDeveloper({ email: 'public@test.invalid', password: 'Developer@2026' }), { status: 404 });
  process.env.APP_ORIGIN = 'http://127.0.0.1:3000';
  t.diagnostic(`Evidence retained in isolated local schema ${schema}; real users and pets untouched`);
});
