const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { Pool } = require('pg');

test('Public access: daily lineage, atomic budget, one-use email verification and reset', { skip: !process.env.LEMON_TEST_DATABASE_URL }, async (t) => {
  const url = new URL(process.env.LEMON_TEST_DATABASE_URL);
  assert.ok(['127.0.0.1','localhost'].includes(url.hostname));
  const admin = new Pool({ connectionString: url.href });
  const schema = `verify_public_${crypto.randomBytes(6).toString('hex')}`;
  await admin.query(`CREATE SCHEMA ${schema}`);
  url.searchParams.set('options', `-c search_path=${schema}`);
  process.env.DATABASE_URL = url.href;
  process.env.DAILY_QUOTA_ENABLED = 'true';
  process.env.AI_MONTHLY_LIMIT_MICROS = '100';
  process.env.AI_CALL_LIMITS_JSON = JSON.stringify({ fixture: 60 });
  const { database, close } = require('./db.cjs');
  t.after(async () => { await close(); await admin.end(); });
  await database().query(fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8'));
  await database().query(fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8'));
  const { enqueue } = require('./jobs.cjs');
  const { reserveCall } = require('./ai-budget.cjs');
  const { hashPassword, authenticate, viewer, digest } = require('./auth.cjs');
  const user = crypto.randomUUID();
  await database().query('INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)', [user, 'quota@test.invalid', await hashPassword('fixture-pass-123')]);
  const extracted = await enqueue(user, 'extract', crypto.randomUUID(), { imageBase64: Buffer.from('source').toString('base64') }, 'test');
  await database().query("UPDATE generation_jobs SET state='success' WHERE id=$1", [extracted.id]);
  const input = { parentJobId: extracted.id, sourceHash: crypto.createHash('sha256').update('source').digest('hex'), candidatesPerStyle: 1 };
  const [generated, replay] = await Promise.all([enqueue(user, 'generate', 'same-key-public-0001', input, 'test'), enqueue(user, 'generate', 'same-key-public-0001', input, 'test')]);
  assert.equal(generated.id, replay.id);
  assert.equal(generated.creation_id, extracted.creation_id);
  assert.equal(generated.cost, 0, 'daily opportunities replace legacy test credits');
  await database().query("UPDATE generation_jobs SET state='success',result=$1 WHERE id=$2", [{ results: [{ imageUrl: '/api/assets/test-identity' }] }, generated.id]);
  const animation = await enqueue(user, 'animate', crypto.randomUUID(), { imageUrl: '/api/assets/test-identity' }, 'test');
  assert.equal(animation.creation_id, extracted.creation_id);
  await database().query("UPDATE generation_jobs SET state='success' WHERE id=$1", [animation.id]);
  const regen = await enqueue(user, 'animate', crypto.randomUUID(), { imageUrl: '/api/assets/test-identity' }, 'test');
  assert.notEqual(regen.creation_id, animation.creation_id, 'manual regeneration consumes a new opportunity');
  await database().query("UPDATE generation_jobs SET state='success' WHERE id=$1", [regen.id]);
  const last = await Promise.allSettled(Array.from({ length: 5 }, (_, i) => enqueue(user, 'extract', crypto.randomUUID(), { imageBase64: `different-${i}` }, 'test')));
  assert.equal(last.filter((result) => result.status === 'fulfilled').length, 1, 'concurrent requests cannot exceed three creations');
  assert.equal(last.filter((result) => result.status === 'rejected' && result.reason.status === 429).length, 4);
  await assert.rejects(enqueue(user, 'generate', crypto.randomUUID(), { ...input, sourceHash: 'foreign' }, 'test'), { status: 400 });
  await database().query("UPDATE creations SET quota_day=quota_day-1 WHERE user_id=$1", [user]);
  await database().query("UPDATE generation_jobs SET state='success' WHERE user_id=$1", [user]);
  const fresh = await enqueue(user, 'extract', crypto.randomUUID(), { imageBase64: 'fresh-day' }, 'test');
  assert.notEqual(fresh.creation_id, extracted.creation_id);

  const worker = crypto.randomUUID();
  const budgetJobs = [fresh, regen];
  for (const job of budgetJobs) {
    job.locked_by = worker;
    await database().query("UPDATE generation_jobs SET state='submitting',locked_by=$1,lease_until=now()+interval '2 minutes' WHERE id=$2", [worker, job.id]);
  }
  const race = await Promise.allSettled(budgetJobs.map((job) => reserveCall(job, 'one', 'fixture')));
  assert.equal(race.filter((result) => result.status === 'fulfilled').length, 1);
  assert.equal(race.filter((result) => result.status === 'rejected' && result.reason.status === 429).length, 1);
  assert.equal((await database().query('SELECT sum(reserved_micros)::int AS amount FROM ai_reservations')).rows[0].amount, 60);
  const winner = budgetJobs[race.findIndex((result) => result.status === 'fulfilled')];
  await assert.rejects(reserveCall(winner, 'one', 'fixture'), /already reserved/);
  await assert.rejects(reserveCall(winner, 'other', 'unknown-model'), { status: 503 });
  await assert.rejects(reserveCall({ ...winner, locked_by: crypto.randomUUID() }, 'other', 'fixture'), /lease lost/);
  await database().query("UPDATE ai_reservations SET period=(period-interval '1 month')::date");
  await assert.rejects(reserveCall(winner, 'other', 'fixture'), { status: 429 }, 'unsettled prior-month calls still reserve capacity');
  process.env.AI_MONTHLY_LIMIT_MICROS = '';
  await assert.rejects(reserveCall(winner, 'other', 'fixture'), { status: 503 });

  process.env.PUBLIC_REGISTRATION = 'true';
  process.env.APP_ORIGIN = 'https://pawnear.test';
  process.env.ASSET_STORAGE = 's3';
  process.env.AI_MONTHLY_LIMIT_MICROS = '100';
  process.env.SMTP_HOST = 'smtp.test.invalid'; process.env.SMTP_PORT = '465';
  process.env.SMTP_USER = 'fixture'; process.env.SMTP_PASSWORD = 'fixture'; process.env.MAIL_FROM = 'test@test.invalid';
  const mail = require('./mail.cjs');
  const delivered = [];
  t.mock.method(mail, 'sendAccountMail', async (email, token, purpose, locale) => delivered.push({ email, token, purpose, locale }));
  const { requestAccountLink, confirmAccount } = require('./accounts.cjs');
  const credentials = { email: 'public@test.invalid', password: 'My-safe-fixture-123' };
  await requestAccountLink({ ...credentials, locale: 'en' }, 'verify');
  assert.equal(delivered.length, 1);
  const first = delivered[0];
  assert.notEqual((await database().query('SELECT token_hash FROM account_tokens')).rows[0].token_hash, first.token);
  await assert.rejects(authenticate(credentials, false), { status: 401 }, 'registration does not accept an unverified password');
  const confirmations = await Promise.allSettled([confirmAccount({ ...first, password: credentials.password }), confirmAccount({ ...first, password: credentials.password })]);
  assert.equal(confirmations.filter((result) => result.status === 'fulfilled').length, 1);
  const session = await authenticate(credentials, false);
  const request = new Request('https://pawnear.test', { headers: { cookie: session.cookie.split(';')[0] } });
  assert.equal((await viewer(request)).id, session.user.id);
  await requestAccountLink(credentials, 'reset');
  const reset = delivered[1];
  await confirmAccount({ ...reset, password: 'Replaced-fixture-123' });
  await assert.rejects(viewer(request), { status: 401 });
  await assert.rejects(confirmAccount({ ...reset, password: credentials.password }), { status: 400 });
  await assert.rejects(authenticate(credentials, false), { status: 401 });
  await authenticate({ ...credentials, password: 'Replaced-fixture-123' }, false);
  await requestAccountLink(credentials, 'reset');
  const expired = delivered[2];
  await database().query("UPDATE account_tokens SET expires_at=now()-interval '1 second' WHERE token_hash=$1", [digest(expired.token)]);
  await assert.rejects(confirmAccount({ ...expired, password: credentials.password }), { status: 400 });
  const before = delivered.length;
  assert.deepEqual(await requestAccountLink({ email: 'absent@test.invalid' }, 'reset'), { sent: true });
  assert.equal(delivered.length, before);
  t.diagnostic(`Isolated schema ${schema}; no real email, provider call or user data mutation`);
});
